{{$duration := "1h"}} # sleep duration
{{$namespaces := 1}}

tuningSets:
- name: Sequence
  parallelismLimitedLoad:
    parallelismLimit: 1

- name: RandomizedSaturationTimeLimited
  randomizedTimeLimitedLoad:
    timeLimit: 1m

name: Hyper-Benchmark
namespace:
  number: {{$namespaces}}
steps:
- name: Start measurements global
  measurements:
  - Identifier: gq_all
    Method: GenericPrometheusQuery
    Params:
      action: start
      metricName: API request latency
      metricVersion: v1
      threshold: 2h
      unit: customUnitsMustBeSpecifiedInConfig
      queries:
      - name: P99_api
        query: histogram_quantile(0.99, sum(rate(apiserver_request_sli_duration_seconds_bucket[%v])) by (le))
      - name: P90_api
        query: histogram_quantile(0.9, sum(rate(apiserver_request_sli_duration_seconds_bucket[%v])) by (le))
      - name: P50_api
        query: histogram_quantile(0.5, sum(rate(apiserver_request_sli_duration_seconds_bucket[%v])) by (le))
      - name: avg_cpu_old
        query: avg(sum by (instance) (rate(node_cpu_seconds_total{mode!="idle", instance!="192.168.137.2:9100"}[%v]))) / 4
      - name: avg_cpu_system_old
        query: avg(sum by (instance) (rate(node_cpu_seconds_total{mode="system", instance!="192.168.137.2:9100"}[%v]))) / 4
      - name: avg_cpu
        query: avg(sum by (instance) (rate(node_cpu_seconds_total{mode!="idle", instance!="192.168.137.2:9100"}[%v])) / 4 * 
          on(instance)(avg by (instance) (node_cpu_scaling_frequency_hertz{instance!="192.168.137.2:9100"}) / avg by (instance) (node_cpu_scaling_frequency_max_hertz{instance!="192.168.137.2:9100"})))
      - name: avg_cpu_system
        query: avg(sum by (instance) (rate(node_cpu_seconds_total{mode="system", instance!="192.168.137.2:9100"}[%v])) / 4 * 
          on(instance)(avg by (instance) (node_cpu_scaling_frequency_hertz{instance!="192.168.137.2:9100"}) / avg by (instance) (node_cpu_scaling_frequency_max_hertz{instance!="192.168.137.2:9100"})))
      - name: avg_cpu_iowait
        query: avg(sum by (instance) (rate(node_cpu_seconds_total{mode="iowait", instance!="192.168.137.2:9100"}[%v])) / 4 * 
          on(instance)(avg by (instance) (node_cpu_scaling_frequency_hertz{instance!="192.168.137.2:9100"}) / avg by (instance) (node_cpu_scaling_frequency_max_hertz{instance!="192.168.137.2:9100"})))
      - name: avg_mem
        query: avg(avg_over_time((node_memory_MemTotal_bytes{instance!="192.168.137.2:9100"} - node_memory_MemAvailable_bytes{instance!="192.168.137.2:9100"})[%v:15s])) / 1024 / 1024
      - name: avg_disk_space
        query: avg(increase(node_disk_written_bytes_total{instance!="192.168.137.2:9100"}[%v])) / 1024 / 1024
      - name: avg_disk_latency
        query: sum(rate(node_disk_write_time_seconds_total{instance!="192.168.137.2:9100"}[%v])) / sum(rate(node_disk_writes_completed_total{instance!="192.168.137.2:9100"}[%v]))
      - name: avg_net
        query: avg(rate(node_network_receive_bytes_total{instance!="192.168.137.2:9100"}[%v])) / 1024 / 1024
      - name: sum_net_total
        query: sum(increase(node_network_receive_bytes_total{instance!="192.168.137.2:9100"}[%v])) / 1024 / 1024
      - name: avg_temp
        query: avg(avg_over_time(node_hwmon_temp_celsius{instance!="192.168.137.2:9100", sensor="temp1", chip="thermal_thermal_zone0"}[%v]))
      # time spent being stalled by resources
      - name: avg_stall_cpu
        query: avg(rate(node_pressure_cpu_waiting_seconds_total{instance!="192.168.137.2:9100"}[%v]))
      - name: avg_stall_mem
        query: avg(rate(node_pressure_memory_stalled_seconds_total{instance!="192.168.137.2:9100"}[%v]))
      - name: avg_stall_io
        query: avg(rate(node_pressure_io_stalled_seconds_total{instance!="192.168.137.2:9100"}[%v]))
      - name: avg_net_retransmission
        query: avg(rate(node_netstat_Tcp_RetransSegs{instance!="192.168.137.2:9100"}[%v]))
      - name: avg_context_switches
        query: avg(rate(node_context_switches_total{instance!="192.168.137.2:9100"}[%v]))
      - name: avg_hardware_interrupts
        query: avg(rate(node_intr_total{instance!="192.168.137.2:9100"}[%v]))

      # PI1
      - name: avg_cpu_old_pi1
        query: avg(sum by (instance) (rate(node_cpu_seconds_total{mode!="idle", instance="192.168.137.10:9100"}[%v]))) / 4
      - name: avg_cpu_system_old_pi1
        query: avg(sum by (instance) (rate(node_cpu_seconds_total{mode="system", instance="192.168.137.10:9100"}[%v]))) / 4
      - name: avg_cpu_pi1
        query: sum by (instance) (rate(node_cpu_seconds_total{mode!="idle", instance="192.168.137.10:9100"}[%v])) / 4 * 
          on(instance)(avg by (instance) (node_cpu_scaling_frequency_hertz{instance="192.168.137.10:9100"}) / avg by (instance) (node_cpu_scaling_frequency_max_hertz{instance="192.168.137.10:9100"}))
      - name: avg_cpu_system_pi1
        query: sum by (instance) (rate(node_cpu_seconds_total{mode="system", instance="192.168.137.10:9100"}[%v])) / 4 * 
          on(instance)(avg by (instance) (node_cpu_scaling_frequency_hertz{instance="192.168.137.10:9100"}) / avg by (instance) (node_cpu_scaling_frequency_max_hertz{instance="192.168.137.10:9100"}))
      - name: avg_cpu_iowait_pi1
        query: sum by (instance) (rate(node_cpu_seconds_total{mode="iowait", instance="192.168.137.10:9100"}[%v])) / 4 * 
          on(instance)(avg by (instance) (node_cpu_scaling_frequency_hertz{instance="192.168.137.10:9100"}) / avg by (instance) (node_cpu_scaling_frequency_max_hertz{instance="192.168.137.10:9100"}))
      - name: avg_mem_pi1
        query: avg(avg_over_time((node_memory_MemTotal_bytes{instance="192.168.137.10:9100"} - node_memory_MemAvailable_bytes{instance="192.168.137.10:9100"})[%v:15s])) / 1024 / 1024
      - name: avg_disk_space_pi1
        query: avg(increase(node_disk_written_bytes_total{instance="192.168.137.10:9100"}[%v])) / 1024 / 1024
      - name: avg_disk_latency_pi1
        query: sum(rate(node_disk_write_time_seconds_total{instance="192.168.137.10:9100"}[%v])) / sum(rate(node_disk_writes_completed_total{instance="192.168.137.10:9100"}[%v]))
      - name: avg_net_pi1
        query: avg(rate(node_network_receive_bytes_total{instance="192.168.137.10:9100"}[%v])) / 1024 / 1024
      - name: sum_net_total_pi1
        query: sum(increase(node_network_receive_bytes_total{instance="192.168.137.10:9100"}[%v])) / 1024 / 1024          
      - name: avg_temp_pi1
        query: avg(avg_over_time(node_hwmon_temp_celsius{instance="192.168.137.10:9100", sensor="temp1", chip="thermal_thermal_zone0"}[%v]))
      - name: avg_cpu_clock_pi1
        query: avg(avg_over_time(node_cpu_scaling_frequency_hertz{instance="192.168.137.10:9100"}[%v]))

      # PI2
      - name: avg_cpu_old_pi2
        query: avg(sum by (instance) (rate(node_cpu_seconds_total{mode!="idle", instance="192.168.137.11:9100"}[%v]))) / 4
      - name: avg_cpu_system_old_pi2
        query: avg(sum by (instance) (rate(node_cpu_seconds_total{mode="system", instance="192.168.137.11:9100"}[%v]))) / 4
      - name: avg_cpu_pi2
        query: sum by (instance) (rate(node_cpu_seconds_total{mode!="idle", instance="192.168.137.11:9100"}[%v])) / 4 * 
          on(instance)(avg by (instance) (node_cpu_scaling_frequency_hertz{instance="192.168.137.11:9100"}) / avg by (instance) (node_cpu_scaling_frequency_max_hertz{instance="192.168.137.11:9100"}))
      - name: avg_cpu_system_pi2
        query: sum by (instance) (rate(node_cpu_seconds_total{mode="system", instance="192.168.137.11:9100"}[%v])) / 4 * 
          on(instance)(avg by (instance) (node_cpu_scaling_frequency_hertz{instance="192.168.137.11:9100"}) / avg by (instance) (node_cpu_scaling_frequency_max_hertz{instance="192.168.137.11:9100"}))
      - name: avg_cpu_iowait_pi2
        query: sum by (instance) (rate(node_cpu_seconds_total{mode="iowait", instance="192.168.137.11:9100"}[%v])) / 4 * 
          on(instance)(avg by (instance) (node_cpu_scaling_frequency_hertz{instance="192.168.137.11:9100"}) / avg by (instance) (node_cpu_scaling_frequency_max_hertz{instance="192.168.137.11:9100"}))
      - name: avg_mem_pi2
        query: avg(avg_over_time((node_memory_MemTotal_bytes{instance="192.168.137.11:9100"} - node_memory_MemAvailable_bytes{instance="192.168.137.11:9100"})[%v:15s])) / 1024 / 1024
      - name: avg_disk_space_pi2
        query: avg(increase(node_disk_written_bytes_total{instance="192.168.137.11:9100"}[%v])) / 1024 / 1024
      - name: avg_disk_latency_pi2
        query: sum(rate(node_disk_write_time_seconds_total{instance="192.168.137.11:9100"}[%v])) / sum(rate(node_disk_writes_completed_total{instance="192.168.137.11:9100"}[%v]))
      - name: avg_net_pi2
        query: avg(rate(node_network_receive_bytes_total{instance="192.168.137.11:9100"}[%v])) / 1024 / 1024
      - name: sum_net_total_pi2
        query: sum(increase(node_network_receive_bytes_total{instance="192.168.137.11:9100"}[%v])) / 1024 / 1024
      - name: avg_temp_pi2
        query: avg(avg_over_time(node_hwmon_temp_celsius{instance="192.168.137.11:9100", sensor="temp1", chip="thermal_thermal_zone0"}[%v]))
      - name: avg_cpu_clock_pi2
        query: avg(avg_over_time(node_cpu_scaling_frequency_hertz{instance="192.168.137.11:9100"}[%v]))


      # PI3
      - name: avg_cpu_old_pi3
        query: avg(sum by (instance) (rate(node_cpu_seconds_total{mode!="idle", instance="192.168.137.12:9100"}[%v]))) / 4
      - name: avg_cpu_system_old_pi3
        query: avg(sum by (instance) (rate(node_cpu_seconds_total{mode="system", instance="192.168.137.12:9100"}[%v]))) / 4
      - name: avg_cpu_pi3
        query: sum by (instance) (rate(node_cpu_seconds_total{mode!="idle", instance="192.168.137.12:9100"}[%v])) / 4 * 
          on(instance)(avg by (instance) (node_cpu_scaling_frequency_hertz{instance="192.168.137.12:9100"}) / avg by (instance) (node_cpu_scaling_frequency_max_hertz{instance="192.168.137.12:9100"}))
      - name: avg_cpu_system_pi3
        query: sum by (instance) (rate(node_cpu_seconds_total{mode="system", instance="192.168.137.12:9100"}[%v])) / 4 * 
          on(instance)(avg by (instance) (node_cpu_scaling_frequency_hertz{instance="192.168.137.12:9100"}) / avg by (instance) (node_cpu_scaling_frequency_max_hertz{instance="192.168.137.12:9100"}))
      - name: avg_cpu_iowait_pi3
        query: sum by (instance) (rate(node_cpu_seconds_total{mode="iowait", instance="192.168.137.12:9100"}[%v])) / 4 * 
          on(instance)(avg by (instance) (node_cpu_scaling_frequency_hertz{instance="192.168.137.12:9100"}) / avg by (instance) (node_cpu_scaling_frequency_max_hertz{instance="192.168.137.12:9100"}))
      - name: avg_mem_pi3
        query: avg(avg_over_time((node_memory_MemTotal_bytes{instance="192.168.137.12:9100"} - node_memory_MemAvailable_bytes{instance="192.168.137.12:9100"})[%v:15s])) / 1024 / 1024
      - name: avg_disk_space_pi3
        query: avg(increase(node_disk_written_bytes_total{instance="192.168.137.12:9100"}[%v])) / 1024 / 1024
      - name: avg_disk_latency_pi3
        query: sum(rate(node_disk_write_time_seconds_total{instance="192.168.137.12:9100"}[%v])) / sum(rate(node_disk_writes_completed_total{instance="192.168.137.12:9100"}[%v]))
      - name: avg_net_pi3
        query: avg(rate(node_network_receive_bytes_total{instance="192.168.137.12:9100"}[%v])) / 1024 / 1024
      - name: sum_net_total_pi3
        query: sum(increase(node_network_receive_bytes_total{instance="192.168.137.12:9100"}[%v])) / 1024 / 1024
      - name: avg_temp_pi3
        query: avg(avg_over_time(node_hwmon_temp_celsius{instance="192.168.137.12:9100", sensor="temp1", chip="thermal_thermal_zone0"}[%v]))
      - name: avg_cpu_clock_pi3
        query: avg(avg_over_time(node_cpu_scaling_frequency_hertz{instance="192.168.137.12:9100"}[%v]))


      # PI4
      - name: avg_cpu_old_pi4
        query: avg(sum by (instance) (rate(node_cpu_seconds_total{mode!="idle", instance="192.168.137.13:9100"}[%v]))) / 4
      - name: avg_cpu_system_old_pi4
        query: avg(sum by (instance) (rate(node_cpu_seconds_total{mode="system", instance="192.168.137.13:9100"}[%v]))) / 4
      - name: avg_cpu_pi4
        query: sum by (instance) (rate(node_cpu_seconds_total{mode!="idle", instance="192.168.137.13:9100"}[%v])) / 4 * 
          on(instance)(avg by (instance) (node_cpu_scaling_frequency_hertz{instance="192.168.137.13:9100"}) / avg by (instance) (node_cpu_scaling_frequency_max_hertz{instance="192.168.137.13:9100"}))
      - name: avg_cpu_system_pi4
        query: sum by (instance) (rate(node_cpu_seconds_total{mode="system", instance="192.168.137.13:9100"}[%v])) / 4 * 
          on(instance)(avg by (instance) (node_cpu_scaling_frequency_hertz{instance="192.168.137.13:9100"}) / avg by (instance) (node_cpu_scaling_frequency_max_hertz{instance="192.168.137.13:9100"}))
      - name: avg_cpu_iowait_pi4
        query: sum by (instance) (rate(node_cpu_seconds_total{mode="iowait", instance="192.168.137.13:9100"}[%v])) / 4 * 
          on(instance)(avg by (instance) (node_cpu_scaling_frequency_hertz{instance="192.168.137.13:9100"}) / avg by (instance) (node_cpu_scaling_frequency_max_hertz{instance="192.168.137.13:9100"}))
      - name: avg_mem_pi4
        query: avg(avg_over_time((node_memory_MemTotal_bytes{instance="192.168.137.13:9100"} - node_memory_MemAvailable_bytes{instance="192.168.137.13:9100"})[%v:15s])) / 1024 / 1024
      - name: avg_disk_space_pi4
        query: avg(increase(node_disk_written_bytes_total{instance="192.168.137.13:9100"}[%v])) / 1024 / 1024
      - name: avg_disk_latency_pi4
        query: sum(rate(node_disk_write_time_seconds_total{instance="192.168.137.13:9100"}[%v])) / sum(rate(node_disk_writes_completed_total{instance="192.168.137.13:9100"}[%v]))
      - name: avg_net_pi4
        query: avg(rate(node_network_receive_bytes_total{instance="192.168.137.13:9100"}[%v])) / 1024 / 1024
      - name: sum_net_total_pi4
        query: sum(increase(node_network_receive_bytes_total{instance="192.168.137.13:9100"}[%v])) / 1024 / 1024
      - name: avg_temp_pi4
        query: avg(avg_over_time(node_hwmon_temp_celsius{instance="192.168.137.13:9100", sensor="temp1", chip="thermal_thermal_zone0"}[%v]))
      - name: avg_cpu_clock_pi4
        query: avg(avg_over_time(node_cpu_scaling_frequency_hertz{instance="192.168.137.13:9100"}[%v]))


      # PI5
      - name: avg_cpu_old_pi5
        query: avg(sum by (instance) (rate(node_cpu_seconds_total{mode!="idle", instance="192.168.137.14:9100"}[%v]))) / 4
      - name: avg_cpu_system_old_pi5
        query: avg(sum by (instance) (rate(node_cpu_seconds_total{mode="system", instance="192.168.137.14:9100"}[%v]))) / 4
      - name: avg_cpu_pi5
        query: sum by (instance) (rate(node_cpu_seconds_total{mode!="idle", instance="192.168.137.14:9100"}[%v])) / 4 * 
          on(instance)(avg by (instance) (node_cpu_scaling_frequency_hertz{instance="192.168.137.14:9100"}) / avg by (instance) (node_cpu_scaling_frequency_max_hertz{instance="192.168.137.14:9100"}))
      - name: avg_cpu_system_pi5
        query: sum by (instance) (rate(node_cpu_seconds_total{mode="system", instance="192.168.137.14:9100"}[%v])) / 4 * 
          on(instance)(avg by (instance) (node_cpu_scaling_frequency_hertz{instance="192.168.137.14:9100"}) / avg by (instance) (node_cpu_scaling_frequency_max_hertz{instance="192.168.137.14:9100"}))
      - name: avg_cpu_iowait_pi5
        query: sum by (instance) (rate(node_cpu_seconds_total{mode="iowait", instance="192.168.137.14:9100"}[%v])) / 4 * 
          on(instance)(avg by (instance) (node_cpu_scaling_frequency_hertz{instance="192.168.137.14:9100"}) / avg by (instance) (node_cpu_scaling_frequency_max_hertz{instance="192.168.137.14:9100"}))
      - name: avg_mem_pi5
        query: avg(avg_over_time((node_memory_MemTotal_bytes{instance="192.168.137.14:9100"} - node_memory_MemAvailable_bytes{instance="192.168.137.14:9100"})[%v:15s])) / 1024 / 1024
      - name: avg_disk_space_pi5
        query: avg(increase(node_disk_written_bytes_total{instance="192.168.137.14:9100"}[%v])) / 1024 / 1024
      - name: avg_disk_latency_pi5
        query: sum(rate(node_disk_write_time_seconds_total{instance="192.168.137.14:9100"}[%v])) / sum(rate(node_disk_writes_completed_total{instance="192.168.137.14:9100"}[%v]))
      - name: avg_net_pi5
        query: avg(rate(node_network_receive_bytes_total{instance="192.168.137.14:9100"}[%v])) / 1024 / 1024
      - name: sum_net_total_pi5
        query: sum(increase(node_network_receive_bytes_total{instance="192.168.137.14:9100"}[%v])) / 1024 / 1024
      - name: avg_temp_pi5
        query: avg(avg_over_time(node_hwmon_temp_celsius{instance="192.168.137.14:9100", sensor="temp1", chip="thermal_thermal_zone0"}[%v]))
      - name: avg_cpu_clock_pi5
        query: avg(avg_over_time(node_cpu_scaling_frequency_hertz{instance="192.168.137.14:9100"}[%v]))

- name: Sleep
  measurements:
  - Identifier: sleep
    Method: Sleep
    Params:
      duration: {{$duration}}

- name: Gather measurements global
  measurements:
  - Identifier: gq_all
    Method: GenericPrometheusQuery
    Params:
      action: gather
      enableViolations: true
