{{$duration := "60s"}} # sleep duration
{{$namespaces := 1}}

{{$countPod := 60}}
{{$countStateful := 60}}
{{$countJob := 30}}

tuningSets:
- name: Sequence
  parallelismLimitedLoad:
    parallelismLimit: 1

- name: RandomizedSaturationTimeLimited
  randomizedTimeLimitedLoad:
    timeLimit: 1m

name: Hyper-Benchmark
namespace:
  number: {{$namespaces}}
steps:
- name: Start measurements global
  measurements:
  - Identifier: gq_all
    Method: GenericPrometheusQuery
    Params:
      action: start
      metricName: API request latency
      metricVersion: v1
      unit: s,s,s,cpus,MB,MB,s,MB
      queries:
        - name: P99_api
          query: histogram_quantile(0.99, sum(rate(apiserver_request_sli_duration_seconds_bucket[%v])) by (le))
        - name: P90_api
          query: histogram_quantile(0.9, sum(rate(apiserver_request_sli_duration_seconds_bucket[%v])) by (le))
        - name: P50_api
          query: histogram_quantile(0.5, sum(rate(apiserver_request_sli_duration_seconds_bucket[%v])) by (le))
        - name: avg_cpu
          query: avg(sum by (instance) (rate(node_cpu_seconds_total{mode!="idle", instance!="192.168.137.2:9100"}[%v])))
        - name: avg_cpu_system
          query: avg(sum by (instance) (rate(node_cpu_seconds_total{mode="system", instance!="192.168.137.2:9100"}[%v])))          
        - name: avg_mem
          query: avg(avg_over_time((node_memory_MemTotal_bytes{instance!="192.168.137.2:9100"} - node_memory_MemAvailable_bytes{instance!="192.168.137.2:9100"})[%v:1s])) / 1024 / 1024
        - name: avg_disk_space
          query: avg(increase(node_disk_written_bytes_total{instance!="192.168.137.2:9100"}[%v])) / 1024 / 1024
        - name: avg_disk_latency
          query: avg(rate(node_disk_write_time_seconds_total{instance!="192.168.137.2:9100"}[%v]))
        - name: avg_net
          query: avg(rate(node_network_receive_bytes_total{instance!="192.168.137.2:9100"}[%v])) / 1024 / 1024
        - name: sum_net_total
          query: sum(increase(node_network_receive_bytes_total{instance!="192.168.137.2:9100"}[%v])) / 1024 / 1024

  - Identifier: APIResponsivenessPrometheus
    Method: APIResponsivenessPrometheus
    Params:
      action: start

  - Identifier: PodStartupLatency
    Method: PodStartupLatency
    Params:
      action: start
      labelSelector: group = load
      threshold: 1h

- name: Creating services
  phases:
  - namespaceRange:
      min: 1
      max: {{$namespaces}}
    replicasPerNamespace: 1
    tuningSet: Sequence
    objectBundle:
    - basename: service
      objectTemplatePath: service.yaml

- name: Start measurement for waiting for pods
  measurements:
  - Method: WaitForControlledPodsRunning
    Instances:
    - Identifier: WaitForRunningDeployments
      Params:
        apiVersion: apps/v1
        kind: Deployment

    - Identifier: WaitForRunningStatefulSets
      Params:
        apiVersion: apps/v1
        kind: StatefulSet

    - Identifier: WaitForRunningDaemonSets
      Params:
        apiVersion: apps/v1
        kind: DaemonSet

    - Identifier: WaitForRunningJobs
      Params:
        apiVersion: batch/v1
        kind: Job

    Params:
      action: start
      labelSelector: group = load
      operationTimeout: 15m
  
- name: Creating objects
  phases:
  - namespaceRange:
      min: 1
      max: {{$namespaces}}
    replicasPerNamespace: 1
    tuningSet: RandomizedSaturationTimeLimited
    objectBundle:
    
    - basename: daemonset
      objectTemplatePath: daemonset.yaml
      templateFillMap:
        Image: liamisko123/test:v1

    - basename: my-configmap
      objectTemplatePath: configmap.yaml

    - basename: my-secret
      objectTemplatePath: secret.yaml

    - basename: my-deployment
      objectTemplatePath: deployment.yaml
      templateFillMap:
        EnableDNSTests: false
        ReplicasMin: {{$countPod}}
        ReplicasMax: {{$countPod}}
        SvcName: my-service
        Image: liamisko123/test:v1

    - basename: my-job
      objectTemplatePath: job.yaml
      templateFillMap:
        ReplicasMin: {{$countJob}}
        ReplicasMax: {{$countJob}}
        Image: liamisko123/test:v2

    - basename: my-statefulset
      objectTemplatePath: statefulset_service.yaml

    - basename: my-statefulset
      objectTemplatePath: statefulset.yaml
      templateFillMap:
        ReplicasMin: {{$countStateful}}
        ReplicasMax: {{$countStateful}}
        Image: registry.k8s.io/pause:3.9

- name: Waiting for pods to be running
  measurements:
  - Method: WaitForControlledPodsRunning
    Instances:
     - Identifier: WaitForRunningDeployments
     - Identifier: WaitForRunningStatefulSets
     - Identifier: WaitForRunningDaemonSets
     - Identifier: WaitForRunningJobs
    Params:
      action: gather

- name: Sleep
  measurements:
  - Identifier: sleep
    Method: Sleep
    Params:
      duration: {{$duration}}

# BEGIN scheduler throughput
# BEGIN pod-startup-latency

- name: Gather measurements global
  measurements:
  - Identifier: gq_all
    Method: GenericPrometheusQuery
    Params:
      action: gather
      enableViolations: true

  - Identifier: APIResponsivenessPrometheus
    Method: APIResponsivenessPrometheus
    Params:
      action: gather

  - Identifier: PodStartupLatency
    Method: PodStartupLatency
    Params:
      action: gather
  
