apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Name}}
spec:
  replicas: {{.ReplicasMin}}
  selector:
    matchLabels:
      app: {{.Name}}
      group: load
  template:
    metadata:
      labels:
        app: {{.Name}}
        group: load
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - arm64
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                - pi5
      containers:
      - name: app
        image: {{.Image}}
        resources:
          requests:
            cpu: "5m"
            memory: "16Mi"
