apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Name}}
  labels:
    group: load_small
spec:
  podManagementPolicy: Parallel
  # serviceName: {{.Name}}
  replicas: {{.ReplicasMin}}
  selector:
    matchLabels:
      app: {{.Name}}
      group: load_small
  template:
    metadata:
      labels:
        app: {{.Name}}
        group: load_small
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              # Requirement 1: Must still be arm64
              - key: kubernetes.io/arch
                operator: In
                values:
                - arm64
              # Requirement 2: Must NOT be pi5
              - key: kubernetes.io/hostname
                operator: In
                values:
                - pi5
      containers:
      - name: app
        image: {{.Image}}
        volumeMounts:
        - name: storage
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-path"
      resources:
        requests:
          storage: 10Mi