apiVersion: v1
kind: Pod
metadata:
  name: pod-name-{{.JobName}}-{{.Iteration}}-{{.Replica}}
  labels:
    app: bench-test
    app: kube-burner-pod
spec:
  nodeSelector:
    kubernetes.io/arch: arm64
    device: edge
  containers:
    - name: bench-test
      image: liamisko123/test:v1