metricsEndpoints:
  - endpoint: http://localhost:9090
    step: 1s
    metrics: [metrics.yaml]
    indexer:
      type: elastic
      esServers: ["https://elastic:{{.ELASTIC_PASSWORD}}@192.168.137.1:9200"]
      defaultIndex: bench_metrics
      insecureSkipVerify: true

global:
  gc: true
  measurements:
    - name: podLatency
      thresholds:
        - conditionType: Ready
          metric: P99
          threshold: 20s
    - name: serviceLatency
      svcTimeout: 5s
    - name: jobLatency
    - name: nodeLatency
    - name: pvcLatency
    # Note: The following require KubeVirt and CDI to be present
    # - name: vmiLatency
    # - name: dataVolumeLatency
    # - name: volumeSnapshotLatencyc
    # - name: vmimLatency

jobs:
  - name: stress-0
    jobIterations: 3
    namespace: burner-test
    namespacedIterations: false
    preLoadImages: true
    cleanup: true
    waitWhenFinished: true
    qps: 5
    burst: 5
    objects:
      - objectTemplate: job.yaml
        replicas: 10

  # - name: stress-1
  #   jobIterations: 1
  #   namespace: burner-test
  #   namespacedIterations: false
  #   preLoadImages: true
  #   cleanup: true
  #   podWait: true
  #   waitWhenFinished: true
  #   jobPause: 30s
  #   qps: 5
  #   burst: 5
  #   objects:
  #     - objectTemplate: pod.yaml
  #       replicas: 10

#   - name: stress-2
#     jobIterations: 1
#     namespace: burner-test
#     namespacedIterations: false
#     preLoadImages: true
#     cleanup: true
#     podWait: true
#     waitWhenFinished: true
#     qps: 5
#     burst: 5
#     objects:
#       - objectTemplate: pod.yaml
#         replicas: 10